<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="5" minorVersionNumber="5" majorServiceNumber="2" buildNumber="6096" updateStamp="_mVs_YXwvEea8_YZoMdL8QA" externalChecksum="1229514692:507989954" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Applicant">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Applicant"/>
        <datastorePersistent manuallyCreated="true" value="false"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Skydiver" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="Skydiver"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="Age"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="Weight"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Gender" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="Gender"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Risk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="Risk"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
